name: vista
channels:
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - aiohttp=3.7.4
  - alsa-lib=1.2.3
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=3.0.4
  - charls=2.2.0
  - click=8.0.1
  - cloudpickle=1.6.0
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - dask-core=2021.7.2
  - dbus=1.13.18
  - descartes=1.1.0
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - fsspec=2021.7.0
  - geos=3.9.1
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.68.3
  - glib-tools=2.68.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - h5py=2.10.0
  - harfbuzz=2.8.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - intel-openmp=2021.3.0
  - jasper=1.900.1
  - jpeg=9d
  - jxrlib=1.1
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopencv=4.5.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.17.2
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.6.2
  - ninja=1.10.2
  - nspr=4.30
  - nss=3.67
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - packaging=21.0
  - partd=1.2.0
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.2
  - pixman=0.40.0
  - protobuf=3.17.2
  - py-opencv=4.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytorch=1.8.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.18.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - shapely=1.7.1
  - sip=4.19.13
  - sk-video=1.1.10
  - snappy=1.1.8
  - sqlite=3.36.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-gpu=2.4.1
  - termcolor=1.1.0
  - tifffile=2020.6.3
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.8.1
  - torchvision=0.2.2
  - tornado=6.1
  - tqdm=4.62.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.6
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - attrdict==2.0.1
    - dill==0.3.4
    - ffio==0.1.0
    - flatbuffers==1.12
    - freetype-py==2.2.0
    - future==0.18.2
    - gast==0.3.3
    - googleapis-common-protos==1.53.0
    - grpcio==1.32.0
    - gviz-api==1.9.0
    - keras-unet==0.1.2
    - numpy==1.19.5
    - openexr==1.3.2
    - promise==2.3
    - psutil==5.8.0
    - pyglet==1.5.18
    - pyopengl==3.1.0
    - pyrender==0.1.45
    - simple-pid==1.0.1
    - six==1.15.0
    - tensorboard-plugin-profile==2.5.0
    - tensorflow-addons==0.14.0
    - tensorflow-datasets==4.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-graphics==2021.8.6
    - tensorflow-metadata==1.2.0
    - trimesh==3.9.27
    - typeguard==2.12.1
    - typing-extensions==3.7.4.3
